/* eslint max-len: [2, 1000, 4] */
module.exports = {
  title: 'Conoce a nuestro staff',
  sectionUrl: 'escuela',
  items: [{
    title: 'GLORIA ZUÑIGA WEHBER',
    subtitle: 'GLORIA ZUÑIGA WEHBER',
    intro: '',
    image: 'https://www.dropbox.com/s/s02dsqogkixpk4x/Img-Gloria-Zuniga.png?dl=0',
    content: [
      'Gloria inició sus clases de baile a los 3 años de edad en las disciplinas de ballet y jazz con la maestra Sandra Araiza. Un año después continuó sus estudios en la escuela de danza Gloria Campobello obteniendo su certificado como Técnica de Danza a los 17 años. Tres años más tarde se certificó como Maestra de Danza avalada por la Secretaría de Educación Pública (SEP).',
      'Siempre con mucha energía y buscando superarse, a los 18 años se certificó como Maestra de Aerobics por ISAT (Institute School of Aerobic Training) y en 1992 se graduó en la Universidad de San Diego State como Licenciada en Danza donde participó durante 4 años en la compañía de esta Universidad, realizando presentaciones en teatros de Los Angeles, San Diego, Tijuana y Ensenada.',
      'También formó parte de la compañía de Danza de Baja California durante dos años, lo cual implicó gran disciplina y sacrificio; gracias a este esmero participó como solista en el Ballet "Cascanueces" en Diciembre de 1994.',
      'Gloria es una persona muy comprometida con su carrera y busca estar actualizada en las últimas técnicas de danza por lo que a tomado cursos como:',
      [
        'GUS (Giordiano Workshop) en Monterrey, N.L. en 2001',
        'Curso para maestros en la escuela "Broadway Dance Center" de Nueva York en 2006.',
        'The Pulse en los Angeles C.A EN 2009',
        'Nuvo workshop en Long Beach en 2014',
        'Jump workshop en Monterrey, Nuevo León en 2015',
        'Curso de Anatomía aplicado a maestros de Danza en 2016',
        'Dance Teacher Summit en Long Beach, CA. - 2016, 2017 y 2018',
      ],
      'En el año 2014 funda junto con Alicia Luna el grupo Pas de Chat el cual tiene como objetivo identificar, proyectar y destacar el talento exigente de las alumnas de la Academia de Danza Pavlova para que las representen en competencias locales, regionales, nacionales e internacionales.',
      'Su objetivo principal es dar lo mejor de ella misma como persona, amiga y representante de la academia proyectando el amor y disciplina por la danza.',
      'Su trayectoria como maestra y directora en Pavlova ha estado marcada por la constancia y motivación que ha transmitido a sus alumnas durante 29 años.',
    ],
  }, {
    title: 'ALICIA LUNA',
    subtitle: 'ALICIA LUNA',
    intro: '',
    image: 'https://www.dropbox.com/s/3b1zex2m6csljia/Img_Alicia-Luna.png?dl=0',
    content: [
      'Lichita inició su preparación en la Academia de Sandra Araiza y posteriormente en la Escuela de Danza Gloria Campobello. Fue así que formó su destino en esta disciplina para convertirse en maestra de danza y posteriormente cofundadora y directora de la Escuela de Danza Pavlova fundada en el año de 1987.',
      'Mientras estuvo en la escuela Campobello, disfrutaba al máximo sus clases como alumna y asistente, donde después de 3 años logró certificarse como Maestra en Técnica de Danza.',
      'En el 2014 fundó, junto con Gloria Zuñiga, el grupo Pas de Chat. Este grupo esta integrado por alumnas destacadas de la escuela de danza Pavlova, quienes representan con orgullo y talento a la escuela en distintas competencias de nivel nacional e internacional.',
      'Buscando siempre estar actualizada y comprometida con su carrera ha tomado cursos como:',
      [
        'Curso de Metodología de la Danza 2014 – Tijuana B.C.',
        'Dance Teachers Summit 2015 – Irvine CA.',
        'Dance Makers 2015 – Los Ángeles CA.',
        'Iniciación a la Danza 2015 – Tijuana B.C.',
        'Curso de Anatomía aplicado a maestros de Danza en 2016 – Tijuana B.C.',
        'Curso Dance Teacher Summit en Long Beach, CA. –2016 y 2017',
        'Actualmente se sigue preparando con clases de Ballet Clásico.',
      ],
      'El tiempo y la entrega que Lichita dedica a sus alumnas, representan la oportunidad de edificar y promover orden, disciplina y convivencia, teniendo como propósito el fomentar los valores que las acompañarán toda su vida, no sólo como un bonito recuerdo, sino como parte de su formación como personas.',
    ],
  }, {
    title: 'MILY WEHBER',
    subtitle: 'MILY WEHBER',
    intro: '',
    image: 'https://www.dropbox.com/s/mdw3idb1vbek96z/Img-Mily-Wehber.png?dl=0',
    content: [
      'Ana Emely Wehber Barreiro, inicia sus estudios a los 4 años de edad en la escuela de danza Gloria Campobello, logrando obtener el título de Técnico en Danza. A los 16 años empieza como asistente de maestra y un año mas tarde la escuela de danza "Nandielo", dandole la oportunidad de dar clases como maestra. Participó como alumna y maestra en la escuela de Danza "Betty Gándara" por 4 años, simultáneamente tomó clases de danza en San Diego State University con maestros como Kelly Grant (Jazz) , George Willis (Contemporáneo). Tomó cursos de Stage 7, Threes Compony y  APA, (Academy of Performing Arts). Workshop de Gus Giordano en Monterrey, ademéas de asistir en Los Angeles CA. con Joe Tremaines, Musicwork Shop, The Pulse. Recientemente participo en Palooza y Novu en Long Beach, CA. con el maestro Yannis Marshall y 24/7 Workshop.',
      'Ha participado en el Carnaval Antifaz Fundación Luz, como coreógrafa en el 2012 y 2013, obteniendo el premio de la mejor coreografía en el 2012.',
      'Curso Palooza en Long Beach CA. – Julio 2017',
      'Empezó a dar clases en la escuela de danza Pavlova, desde que esta abrió sus puertas.',
      '"Mi gran pasión es ser maestra de danza... Ver a mis alumnas crecer, como bailarinas, como disfrutan sus clases, transmitirles el amor por la danza, la constancia , diciplina, ver como logran sus metas, y saber que tu eres parte de estos logros, es una de mis más grandes satisfacciones en la vida." – Miss Mily',
    ],
  }, {
    title: 'ALEJANDRA GUTIERRÉZ',
    subtitle: 'ALEJANDRA GUTIERRÉZ',
    intro: '',
    image: 'https://www.dropbox.com/s/r81hjmxo9niz3pf/Img-Alejandra-Gutierrez.png?dl=0',
    content: [
      'Inicio sus estudios a la edad de 3 años en el colegio de danza Sylvia bajo la dirección de la maestra Silvia Elena Martínez, estudio ahí por más de 15 años en las disciplinas de Jazz, Ballet y Tap, donde tuvo la oportunidad de asistir a varios cursos como NYCDA, Tremaine y Al Gilbert. Fue asistente en la disciplina de Tap.',
      'A la edad de 16 años empezó siendo maestra y asistente en la escuela de danza Ancheyta dando clases de tap y jazz.',
      'A los 19 empezó dando clases en la escuela de danza Pavlova Hipódromo en la disciplina de jazz. Se ha preparado en varios cursos como Dancemakers, Nuvo en long beach, Jump Monterrey, 24/7 en San diego, Dance Teacher Summit LB y DancerPalozza en Long beach.',
      'Coreógrafa en la escuela de danza Coppelia donde sus alumnas obtuvieron varios primeros lugares en la competencia Dance Makers en la disciplina de lirico así como un premio especial por mejor coreografía.',
      'Actualmente forma parte del equipo de trabajo de la escuela Pavlova Hipódromo y es coreógrafa del grupo de competencia Pasdechat by Pavlova con el cual ha viajado a varios concursos nacionales e internacionales, obteniendo varios primeros lugares por sus coreografías y reconocidas becas para sus alumnas, el curso más reconocido que han becado a sus alumnas es Dance Awards.',
      'Es una maestra reconocida por sus coreografías tanto en jazz como en lírico en niveles intermedios y avanzados.',
    ],
  }, {
    title: 'CORINA PERAZA',
    subtitle: 'CORINA PERAZA',
    intro: '',
    image: 'https://www.dropbox.com/s/78ttm4iz875wtir/Img-Corina-Peraza.png?dl=0',
    content: [
      'Corina es originaria de Tijuana y desde muy pequeña empezó a bailar Flamenco. Es hija de la famosa bailarina española Teresa Jaen, miembro del dueto "Teresa y Antonio Jaen". El tener a su madre como instructora, le ha ayudado a desarrollarse cada vez más a través de los años.',
      'Lleva el arte en sus venas, es por ello que Corina comparte con sus estudiantes el mismo sentimiento y pasión por el baile Flamenco. Es sabido que cualquier forma de arte se transforma en comunicación, entonces, qué mejor manera de transmitirlo tan intensamente a sus estudiantes que a través del amor y pasión del baile Flamenco.',
    ],
  }, {
    title: 'MAYRA JIMÉNEZ',
    subtitle: 'MAYRA JIMÉNEZ',
    intro: '',
    image: 'https://www.dropbox.com/s/1ubs0mhib2ca80a/Img_Mayra-Jimenez.png?dl=0',
    content: [
      'Nacio el 4 de Junio del 1988. Mayra desde sus 4 años de edad comenzó a experimentar tomando clases de Jazz, y 2 años después comenzó tomando clases de ballet. Hasta la fecha sigue practicando la danza, habiendo tomado aparte de Ballet y Jazz,  clases de Contemporáneo con Miroslava Wilson y  Hip-Hop con el maestro Omar Silva dentro de la Escuela " Ballet Cámara de la Frontera" del Maestro Rafael Oseguera, habiéndose graduado como Bailarina Clásica y Contemporánea.',
      'Tiene 9 años de experiencia como Maestra impartiendo clases de Jazz, Ballet, y Lirico. Habiendo concluido con cursos de Metodología para la Danza y pedagogía.',
      'Asistiendo al 5to y 6to Congreso Nacional de Danza Jazz en Morelia Michoacán con maestros como: Guillermo Maldonado (barra al piso y pedagogía), Guillermina Gómez y John Lehrer (Jazz), Joshua Bergasse de Nueva York (jazz), Elvin Venegas de Nicaragua (técnica clásica – Ballet), Jermaine Browne de nueva York (hip-hop), Alexis Zanette de Cuba (danza moderna), entre otros. También a tomando el Curso Internacional de Danza Clásica "DANCE IT 2007 y 2008" con la primera Bailarina Irma Morales y Frank Fischer.',
      'Posteriormente obteniendo una beca para formar parte de un grupo de baile de la escuela "Culture Shock Dance Center" en San Diego. Asistio Entre el 2014 y 2015 a un curso de Jazz  y "Hells" con Yanis Marshall (bailarin y maestro Internacional) y una Materclass de ballet con la maestra Elena Tokareva Baltovick; entre otros cursos locales.',
      'Ha participado en varias obras musicales Infantiles como son "Cri-cri y la danza", "El mago de Oz", "Peter Pan", "Alicia en el país de las maravillas", como también en "La fille Mal Garde", "Graduados", "Cascanueces" y "Carmen" presentadas en el Teatro del Cecut.',
      'Su objetivo es transmitir de la manera más correcta todo lo que ha aprendido de la danza, todo lo bueno que le ha dejado e inculcar en el alumnado una disciplina y amor a la danza, a la cultura, al arte, haciéndolas sentir que es una de las mejores maneras para expresar todo aquello que nuestro cuerpo siente.',
    ],
  }, {
    title: 'ELEANA FRANCO',
    subtitle: 'ELEANA FRANCO',
    intro: '',
    image: 'https://www.dropbox.com/s/7xofldjk7cnl2ds/Eleana-Franco.png?dl=0',
    content: [
      'Bailarina, coreógrafa y maestra de danza nacida en Estados Unidos. Inicio sus estudios a la edad de 2 anos en el “Colegio de Danza Sylvia” donde aprendió ballet, tap, flamenco, jazz y hip hop. Varios años después se convirtió en asistente y próximamente en maestra.',
      'Participo en varias importantes obras como es “el cascanueces” junto con la compañía “Moscow ballet” en el Civic Theatre en San Diego y también junto con la “Compañía de danza de Baja California” con Raul Tadeo. También fue participe de la obra infantil “pedro y el lobo” que fue presentada en el CECUT bajo la dirección de Norma Herrera. Continuo con sus estudios en Estados Unidos en la escuela “Coronado School of the Arts” donde estudio varios cursos de historia de la danza, nutrición, improvisación, critica de la danza, coreografía entre muchos otros.',
      'Actualmente se encuentra aplicando estos conocimientos como maestra y busca seguir creciendo para compartir este conocimiento con sus alumnos.',
    ],
  }, {
    title: 'ADRIANA CORAL',
    subtitle: 'ADRIANA CORAL',
    intro: '',
    image: 'https://www.dropbox.com/s/q4kedajs4rgdqe1/Adriana-Coral.png?dl=0',
    content: [
      'Bailarina y maestra que se desarrolla profesionalmente  en el norte de México; miembro fundador de Subterráneo Danza Contemporánea desde hace 17 años, donde su misión es exponer su trabajo como intérprete y colaborador creativo en la realización de espectáculos escénicos. Mantiene una constante búsqueda del lenguaje propio a través de la investigación en diferentes técnicas dancísticas  así como la divulgación de sus conocimientos a través de la docencia, asimismo, busca mantener vínculos estrechos con otros artistas escénicos del país para fortalecer su quehacer  dancístico y contribuir a la difusión del arte.',
    ],
  }, {
    title: 'VICKY SAENZ',
    subtitle: 'VICKY SAENZ',
    intro: '',
    image: 'https://www.dropbox.com/s/7ngb2v9j29d1xd2/Vicky-Saenz.png?dl=0',
    content: [],
  }, {
    title: 'ARIELI ZABICKY',
    subtitle: 'Arieli Zabicky',
    intro: '',
    image: 'https://www.dropbox.com/s/dt09rnnkk7u4b2u/Arieli-Zabicky.png?dl=0',
    content: [
      'Ari Zabicky – Licenciada en danza, bailarina profesional, artista escénico, instructora.',
      'Actualmente laborando con:',
      [
        'Subterráneo Danza Contemporánea como bailarina',
        'Maestra de ballet adulto en Plan D',
        'Maestra de asignatura en Ateneo Universitario',
      ],
      'FORMACIÓN PROFESIONAL',
      ['Técnico en Danza (2010 – 2012)'],
      'Escuela de Danza Gloria Campobello, Tijuana, B.C., México',
      ['Licenciatura en Danza (2012 – 2016)'],
      'Universidad Autónoma De Baja California, Mexicali B.C, México',
      'CURSOS MÁS RECIENTES',
      '2014',
      [
        'Seminario de Metodología para la enseñanza de la Danza Clásica CEART Tijuana. Impartió: Mtro. Rafael Ocegueda',
        'Taller Intensivo de Ballet. Escuela Americana de danza, Mexicali B.C., Impartio: Aldo Kattón',
      ],
      '2015',
      [
        'Taller intensivo "DANZA JAZZ" UABC, Facultad de Artes, Mexicali. B.C., Impartido por: Pedro Garcia Malvaez',
        'Master Class de partnering Facultad de Artes UABC, Licenciatura En danza Impartió Lux Boreal',
        'Congreso Nacional de Danza Jazz – CRAM, Zam. Mich.',
      ],
      '2016',
      [
        'Capacitación en "Contrología" o Método Pilates Nivel 1, Fitness Center, Mexicali B.C., Impartió: Lic. Eunice Hidalgo Palacios',
        'Taller "El cuerpo vacío" Dance Lab, Tijuana, Impartió: Shantí Vera',
      ],
      '2017',
      [
        'Taller de Metodo Feldenkrais "El Huerto Playas de Tijuana" Impartió: Kata Cots',
      ],
      'PARTICIPACIONES',
      '2015',
      [
        'Bailarina invitada en grupo de danza "La Pieza Danza Jazz", Concurso dentro del marco del Congreso Internacional de Danza Jazz Zamora, Michoacán. Participación con la coreografía "CUERPOS", Coreógrafo: Ricardo Zavala, PRIMER LUGAR',
      ],
      '2016',
      [
        'Bailarina en grupo de danza "La Pieza Danza Jazz", Coreografía: Obscuridad Coreógrafo: Ricardo Zavala, Presentación de exhibición en el 8vo concurso del Congreso Internacional de Danza Jazz – Zamora, Michoacán',
        'Bailarina en Grupo de danza "La Pieza Danza Jazz".<br />Obra: "Méjico, una chicanada más".<br />- Bailarina.<br />- Gestión.<br />- Asistente de producción.<br />Dirección general: Ricardo Zavala.<br />Presentaciones:<br />- Teatro UABC, Mexicali B.C.<br />- Teatro Obrero, Zamora Michoacán dentro de Congreso Nacional de Danza Jazz.',
        'Colaboración como bailarina invitada con compañía de danza Bajo la Lápida.<br />Coreógrafo: Armando Leal.<br />Participación en evento de ARMONIA UABC – 2016',
        'OBRA: "Homa´quina".<br />Coreógrafo: Emma G. Davis.<br />Proyecto coreográfico de la Lic. En danza UABC – Mexicali.<br />Estreno: 3 de Junio 2016.<br />- Bailarina.<br />- Gestión.<br />- Montaje coreográfico y de iluminación',
        'Montajes de iluminación en Festival Internacional de Danza Entre Fronteras UABC, Mexicali B.C.<br />- "Quasar" compañía de danza<br />- Taller coreográfico de la UABC<br />Antares Danza contemporánea, Responsable: Hildelena Vazquez',
        'Participación en el taller "Body mind centering"<br />Lic. En Danza, UABC<br />Impartió: Tamar Kipnis',
        'Bailarina en la pieza: "Mis amigos me dicen.."<br />Coreografa: Rosa A. Gomez<br />Actividad dentro de Facultad de Artes UABC',
        'Entijuanarte<br />Montaje de iluminación y traspunte en: "Piezas desordenadas"<br />bajo la dirección de Gregorio Coral',
      ],
      '2017',
      [
        'Bailarina invitada en Subterraneo Danza contemporánea',
        'Bailarina en la obra: Caleidoscopio<br />Direccion: Gregorio Coral',
      ],
    ],
  }, {
    title: 'MARILU AGUILAR',
    subtitle: 'Marilu Aguilar',
    intro: '',
    image: 'https://www.dropbox.com/s/r5idqzlpc7j9iwv/Marilu-Aguilar.png?dl=0',
    content: [
      '<b>Formación Artística</b>',
      '<b>2017</b> Actual residente de la compañía de danza Lux Boreal, Tijuana. <br />Actual integrante y colaboradora coreografica de Tranze Producciones, Mexicali.<br />Residente de Resonancias laboratorio de creacion en CASA, Oaxaca',
      '<b>2016</b> Residente de Centro de Danza y Producción Escénica de Baja California. <br />Integrante de Homa Colectivo de Danza, Mexicali',
      '<b>2015-2016</b> ArcDanz International Dance Program en Puebla; Reves Entrenamiento. <br />Físico en Heredia, Costa Rica; Campin en San Luis Potosi, México',
      '<b>2014-2015</b> Verano Chilango La Cantera, Ciudad de México; Contemporáneo con Nederlands Dans Theatre, San Diego; Congreso La Ruta, Mexicali ',
      '<b>2013-2014</b> Barra al Piso; Congreso de jazz, ballet y contemporáneo La Ruta, Mexicali',
      '<b>2012-2010</b> Integrante del Ballet de Martha Pulido en Tecate; Curso de ballet, jazz, tap y flamenco en San Diego Dance Academy',
      '<br/><b>Experiencia Escénica</b>',
      '<b>2017-2016</b> Bailarina de Medium en Sibu International Dance Festival, Malasia y en Tecate, Mexicali y Los Angeles. Primer lugar en "Agite y Sirva Festival de Videodanza"; Homa´quina en Mexicali, Tijuana y Ensenada; Soft Associations en Tijuana; One en Palm Springs; Biografía en Ocho en Ciudad de México y Puebla; Mentes en Los Ángeles, Costa Rica y Corea del Sur',
      '<b>2015-2013</b> Tercer lugar en Andong Mask Dance Festival and Competition, Corea del Sur; Día Internacional de la danza en Mexicali y Tecate; Encuentro Internacional de Danza Contemporánea Entre Fronteras, Mexicali. ',
      '<b>2012-2010</b> Ballet: Coppelia, El Cascanueces, Atlantis, Danza Fusión, Bicentenario de la Revolución y Día internacional de la danza, Tecate',
      '<br /><b>Experiencia Docente</b>',
      '<b>2017</b> Danza Contemporanea y Fit Ball en Sau de Chat, Jazz Infantil en Escuela de Danza Pavlova; Barre en Studio Barre Fitness, Tijuana',
      '<b>2016</b> Pilates para Adultos Mayores en CEART, Tecate',
      '<b>2016-2015</b> Barrecore, Ballet principiante, Ballet infantil y Jazz intermedio en Academia Idanza; Baby ballet, Ballet infantil, Jazz infantil, Jazz intermedio y Jazz avanzado en Academia Minue',
      '<b>2014-2015</b> Expresión Corporal para niños con capacidades diferentes en CEDI; Jazz en Centro Multidisciplinario Danzxarte; Dance for Fitness en gimnasio Total Fitness; Baby ballet y Jazz infantil en Academia Minue',
      '<b>2010-2012</b> Impartición de Ballet, Jazz, Tap y Danza Árabe en San Diego Dance Academy; Taller de ballet infantil en Centro Cultural Tecate',
    ],
  }, {
    title: 'GIOVANI GONZÁLEZ ALARCÓN',
    subtitle: 'GIOVANI GONZÁLEZ ALARCÓN',
    intro: '',
    image: '/images/escuela/staff/giovani-alarcon.jpg',
    content: [
      'Egresado de la Lic. en Actividad Física y Deporte por la Universidad Autónoma de Baja California, con amplia experiencia en presentaciones profesionales incluyendo participación en shows de la cadena televisiva Telemundo, eventos masivos en Los Ángeles y en Baja California, incluyendo apertura de múltiples conciertos de artistas en la región.',
      'Impartió clases de Cardio Dance y Cardio Hip Hop en diversos gimnasios de la Ciudad de Tijuana. Maestro de Hip-Jazz en los principales estudios de Danza en Tijuana.',
      'Coreógrafo Profesional, forma parte de la compañía de Hip Hop "Culture Shock" en San Diego.',
    ],
  }, {
    title: 'Adriana Coral Pulido',
    subtitle: 'Adriana Coral Pulido',
    intro: '',
    image: '/images/escuela/staff/AdrianaCoral-Pavlova.png',
    content: [
      'Bailarina y maestra que se desarrolla profesionalmente en el norte de México; miembro fundador de Subterráneo Danza Contemporánea desde hace 17 años, donde su misión es exponer su trabajo como intérprete y colaborador creativo en la realización de espectáculos escénicos. Creadora la revista especializada en danza, Escena Cóncava, editada en la ciudad de Tijuana, Baja California. Ha participado como ejecutante dentro de varios festivales a nivel nacional e internacional y realizó el Festival “Mujeres que sueñan”. Fue becado como grupo artístico por el Fondo Especial para la Cultura y las Artes de B.C. (FOECA), para desarrollar la coreografía “Mitología del nómada: escenas para apresar el alma flotante de los trotamundos.”',
      'Dentro de su preparación ha tomado clase con los siguientes reconocidos maestros: Ricardo Peralta, Jo Savino, Ugo Ruíz, Jorge Cerecero, Irma Morales, Edgar Robles, Roberto Robles, Guillermo Maldonado, Lucero Camarena, Vicente Silva, Mijael Rojas, Claudia Lavista, Omar Carum, Khosro Adibi y con la ex primera bailarina rusa del ballet de Kiev, Tatiana Tchevchenco.',
      'Mantiene una constante búsqueda del lenguaje propio a través de la investigación en diferentes técnicas dancísticas así como la divulgación de sus conocimientos a través de la docencia, asimismo, busca mantener vínculos estrechos con otros artistas escénicos del país para fortalecer su quehacer dancístico y contribuir a la difusión del arte.',
    ],
  }, {
    title: 'Martha Lugo Torres',
    subtitle: 'Martha Lugo Torres',
    intro: '',
    image: '/images/escuela/staff/MarthaLugo-Pavlova.png',
    content: [
      'Profesora, bailarina y coreógrafa. Nacida en Tijuana, Baja California. Egresada del técnico en Danza en la Escuela de Danza Gloria Campobello – EDGC (Tijuana, México). Cuenta con formación en ballet clásico, danza española, contemporáneo, flamenco y jazz. Participó en el Ballet del Noroeste de México en El lago de los cisnes, Cascanueces, Don Quijote y Giselle; curso la cátedra de danza impartida por el Ballet Nacional de Cuba. Actualmente funge como maestra y coreógrafa en academias de danza de Tijuana y Rosarito.',
      'Imparte cátedra de acuerdo a las necesidades de cada persona, dependiendo su edad y su conocimiento en la danza, cuidando, ante todo, la salud física de los alumnos. ',
    ],
  }, {
    title: 'María Del Carmen Hechavarria',
    subtitle: 'María Del Carmen Hechavarria',
    intro: '',
    image: '/images/escuela/staff/MariaDelCarmen-Pavlova.png',
    content: [
      'Bailarina solista y maître del Ballet Nacional de Cuba. Inició sus estudios de ballet en la Escuela Nacional de Arte. Sus principales profesores fueron Alicia Alonso, Fernando Alonso, Laura Alonso, Ramona de Sáa, Josefina Méndez, Loipa Araújo, Aurora Bosch, Joaquín Benegas, Rosa Elena Álvarez y Adolfo Roval. Forma parte del Ballet Nacional de Cuba, compañía con la que actúa en las más importantes obras de repertorio de la gran tradición romántico-clásica, así como en creaciones de contemporáneos.',
      'Obtuvo la licenciatura en Arte Danzario por el Instituto Superior de Arte en La Habana, en la Especialidad de Ballet. Ha participado en numerosas giras por América, Europa y Asia, y ha actuado en famosos teatros.',
      'Cercana colaboradora de Alicia Alonso, ha sido su asistente en el montaje de varias coreografías. También ha sido repositora de obras de otros coreógrafos, así como del repertorio tradicional. Su experiencia pedagógica abarca una amplia trayectoria que va desde los cursos de psicoballet, hasta cursos de verano organizados por la Cátedra Alicia Alonso de la Universidad Complutense, de Madrid.',
      'Recibió la Distinción ¨Raúl Gómez García¨ y la Distinción por la cultura Nacional. La primera edición de Alicia Alonso, más allá de la técnica, por la universidad Politécnica de Valencia, y fue presentada en la casa de América en Madrid por Francisco Nieva, miembro de la Real Academia Española.',
    ],
  }, {
    title: 'Andrea Margarita Almaraz González',
    subtitle: 'Andrea Margarita Almaraz González',
    intro: '',
    image: '/images/escuela/staff/Andrea-Pavlova.png',
    content: [
      'Inició su formación de danza a los 4 años de edad en “escuela de danza pavlova” donde aprendió ballet, jazz, flamenco y lírico. A los 7 años tomó  clases de gimnasia durante dos años. A sus 17 años entró a una compañía de danza latina y al transcurso ha ido tomando clases de ritmos latinos.',
      'Empezó siendo asistente de ballet  en escuela de danza pavlova y años después empezó a dar clase de ballet en un academia de artes y un colegio. Ha trabajado de bailarina en conciertos con cantantes locales y de bailarina en un grupo de música versátil como punto clave, maz tekila, la clase y Revelación. Participó en diversos cursos tales como el curso de flamenco con Maria Juncal, curso de flamenco con Cristóbal Reyes, curso de flamenco María Carrasco, curso expression dance, curso salsa fest, entre otros.',
    ],
  },
  ],
};
