/* eslint max-len: [2, 1000, 4] */
export default {
  title: 'Conoce a nuestro staff',
  sectionUrl: 'escuela',
  items: [{
    title: 'GLORIA ZUÑIGA WHEBER',
    subtitle: 'GLORIA ZUÑIGA WHEBER',
    intro: '',
    image: 'https://www.dropbox.com/s/s02dsqogkixpk4x/Img-Gloria-Zuniga.png?dl=0',
    content: [
      'Gloria inició sus clases de baile a los 3 años de edad en las disciplinas de ballet y jazz con la maestra Sandra Araiza. Un año después continuó sus estudios en la escuela de danza Gloria Campobello obteniendo su certificado como Técnica de Danza a los 17 años. Tres años más tarde se certificó como Maestra de Danza avalada por la Secretaría de Educación Pública (SEP).',
      'Siempre con mucha energía y buscando superarse, a los 18 años se certificó como Maestra de Aerobics por ISAT (Institute School of Aerobic Training) y en 1992 se graduó en la Universidad de San Diego State como Licenciada en Danza donde participó durante 4 años en la compañía de esta Universidad, realizando presentaciones en teatros de Los Angeles, San Diego, Tijuana y Ensenada.',
      'También formó parte de la compañía de Danza de Baja California durante dos años, lo cual implicó gran disciplina y sacrificio; gracias a este esmero participó como solista en el Ballet "Cascanueces" en Diciembre de 1994.',
      'Gloria es una persona muy comprometida con su carrera y busca estar actualizada en las últimas técnicas de danza por lo que a tomado cursos como:',
      [
        'GUS (Giordiano Workshop) en Monterrey, N.L. en 2001',
        'Curso para maestros en la escuela "Broadway Dance Center" de Nueva York en 2006.',
        'The Pulse en los Angeles C.A EN 2009',
        'Nuvo workshop en Long Beach en 2014',
        'Jump workshop en Monterrey, Nuevo León en 2015',
        'Curso de Anatomía aplicado a maestros de Danza en 2016',
        'Dance Teacher Summit 2016',
      ],
      'En el año 2014 funda junto con Alicia Luna el grupo Pas de Chat el cual tiene como objetivo identificar, proyectar y destacar el talento exigente de las alumnas de la Academia de Danza Pavlova para que las representen en competencias locales, regionales, nacionales e internacionales.',
      'Su objetivo principal es dar lo mejor de ella misma como persona, amiga y representante de la academia proyectando el amor y disciplina por la danza.',
      'Su trayectoria como maestra y directora en Pavlova ha estado marcada por la constancia y motivación que ha transmitido a sus alumnas durante 29 años.',
    ],
  }, {
    title: 'ALICIA LUNA',
    subtitle: 'ALICIA LUNA',
    intro: '',
    image: 'https://www.dropbox.com/s/3b1zex2m6csljia/Img_Alicia-Luna.png?dl=0',
    content: [
      'Lichita inició su preparación en la Academia de Sandra Araiza y posteriormente en la Escuela de Danza Gloria Campobello. Fue así que formó su destino en esta disciplina para convertirse en maestra de danza y posteriormente cofundadora y directora de la Escuela de Danza Pavlova fundada en el año de 1987.',
      'Mientras estuvo en la escuela Campobello, disfrutaba al máximo sus clases como alumna y asistente, donde después de 3 años logró certificarse como Maestra en Técnica de Danza.',
      'En el 2014 fundó, junto con Gloria Zuñiga, el grupo Pas de Chat. Este grupo esta integrado por alumnas destacadas de la escuela de danza Pavlova, quienes representan con orgullo y talento a la escuela en distintas competencias de nivel nacional e internacional.',
      'Buscando siempre estar actualizada y comprometida con su carrera ha tomado cursos como:',
      [
        'Curso de Metodología de la Danza 2014 – Tijuana B.C.',
        'Dance Teachers Summit 2015 – Irvine CA.',
        'Dance Makers 2015 – Los Ángeles CA.',
        'Iniciación a la Danza 2015 – Tijuana B.C.',
        'Curso de Anatomía aplicado a maestros de Danza en 2016 – Tijuana B.C.',
        'Curso Dance Teacher Summit en Long Beach CA. – Julio 2017',
        'Actualmente se sigue preparando con clases de Ballet Clásico.',
      ],
      'El tiempo y la entrega que Lichita dedica a sus alumnas, representan la oportunidad de edificar y promover orden, disciplina y convivencia, teniendo como propósito el fomentar los valores que las acompañarán toda su vida, no sólo como un bonito recuerdo, sino como parte de su formación como personas.',
    ],
  }, {
    title: 'MILY WEHBER',
    subtitle: 'MILY WEHBER',
    intro: '',
    image: 'https://www.dropbox.com/s/mdw3idb1vbek96z/Img-Mily-Wehber.png?dl=0',
    content: [
      'Ana Emely Wehber Barreiro, inicia sus estudios a los 4 años de edad en la escuela de danza Gloria Campobello, logrando obtener el título de Técnico en Danza. A los 16 años empieza como asistente de maestra y un año mas tarde la escuela de danza "Nandielo", dandole la oportunidad de dar clases como maestra. Participó como alumna y maestra en la escuela de Danza "Betty Gándara" por 4 años, simultáneamente tomó clases de danza en San Diego State University con maestros como Kelly Grant (Jazz) , George Willis (Contemporáneo). Tomó cursos de Stage 7, Threes Compony y  APA, (Academy of Performing Arts). Workshop de Gus Giordano en Monterrey, ademéas de asistir en Los Angeles CA. con Joe Tremaines, Musicwork Shop, The Pulse. Recientemente participo en Palooza y Novu en Long Beach, CA. con el maestro Yannis Marshall y 24/7 Workshop.',
      'Ha participado en el Carnaval Antifaz Fundación Luz, como coreógrafa en el 2012 y 2013, obteniendo el premio de la mejor coreografía en el 2012.',
      'Curso Palooza en Long Beach CA. – Julio 2017',
      'Empezó a dar clases en la escuela de danza Pavlova, desde que esta abrió sus puertas.',
      '"Mi gran pasión es ser maestra de danza... Ver a mis alumnas crecer, como bailarinas, como disfrutan sus clases, transmitirles el amor por la danza, la constancia , diciplina, ver como logran sus metas, y saber que tu eres parte de estos logros, es una de mis más grandes satisfacciones en la vida." – Miss Mily',
    ],
  }, {
    title: 'ALEJANDRA GUTIERRÉZ',
    subtitle: 'ALEJANDRA GUTIERRÉZ',
    intro: '',
    image: 'https://www.dropbox.com/s/r81hjmxo9niz3pf/Img-Alejandra-Gutierrez.png?dl=0',
    content: [
      'Inicio sus estudios a la edad de 3 años en el colegio de danza Sylvia bajo la dirección de la maestra Silvia Elena Martínez, estudio ahí por más de 15 años en las disciplinas de Jazz, Ballet y Tap, donde tuvo la oportunidad de asistir a varios cursos como NYCDA, Tremaine y Al Gilbert. Fue asistente en la disciplina de Tap.',
      'A la edad de 16 años empezó siendo maestra y asistente en la escuela de danza Ancheyta dando clases de tap y jazz.',
      'A los 19 empezó dando clases en la escuela de danza Pavlova Hipódromo en la disciplina de jazz. Se ha preparado en varios cursos como Dancemakers, Nuvo en long beach, Jump Monterrey, 24/7 en San diego, Dance Teacher Summit LB y DancerPalozza en Long beach.',
      'Coreógrafa en la escuela de danza Coppelia donde sus alumnas obtuvieron varios primeros lugares en la competencia Dance Makers en la disciplina de lirico así como un premio especial por mejor coreografía.',
      'Actualmente forma parte del equipo de trabajo de la escuela Pavlova Hipódromo y es coreógrafa del grupo de competencia Pasdechat by Pavlova con el cual ha viajado a varios concursos nacionales e internacionales, obteniendo varios primeros lugares por sus coreografías y reconocidas becas para sus alumnas, el curso más reconocido que han becado a sus alumnas es Dance Awards.',
      'Es una maestra reconocida por sus coreografías tanto en jazz como en lírico en niveles intermedios y avanzados.',
    ],
  }, {
    title: 'TANIA ADAME',
    subtitle: 'TANIA ADAME',
    intro: '',
    image: 'https://www.dropbox.com/s/s8rs8vyfju6cmic/Img-Tania-Adame.png?dl=0',
    content: [
      'Inició sus estudios de danza a los 3 años y medio en Tijuana, B. C. Egresó de la carrera de Técnico en Danza en el 2010 de la Escuela de Danza Gloria Campobello.',
      'Su formación como bailarina incluye danza clásica, danza española, danza jazz, tap y danza contemporánea. Desde hace 8 años se ha dedicado a la docencia de las distintas danzas en diferentes escuelas.',
      'Integrante del Grupo de Danza Minerva Tapia, ha participado en producciones como 16th Annual Noche Cultural de Estudios Chicanos en la Universidad de California Riverside, "Vive la Cultura con Todos los Sentidos" en Sinaloa, México, "Border Dancers" en la ciudad de Nueva York, diferentes ediciones de Entijuanarte, Cuerpos en tránsito y "Celebración anual de la danza" en Rosario, Argentina en el año 2011 por mencionar algunos. Fue becaria del programa Talentos Artísticos, Valores de Baja California en el ciclo 2008 – 2010 dirigido por el Instituto de Cultura de Baja California. Nombrada como una de las "13 promesas artísticas" por el periódico Frontera en el año 2005.',
      'Ha asistido a varios cursos como el curso de verano impartido por el Ballet de Monterrey y la Cátedra de danza del Ballet Nacional de Cuba en La Habana.',
      'Actualmente continúa su entrenamiento con clases de danza contemporánea y ballet.',
    ],
  }, {
    title: 'RHONAL RUVALCABA',
    subtitle: 'RHONAL RUVALCABA',
    intro: '',
    image: 'https://www.dropbox.com/s/izw96o5i39cabla/Img_Rhonal-Ruvalcaba-2.png?dl=0',
    content: [
      'Inicio sus estudios de danza a la edad de 14 años, descubriendo en ella su vocación! Su preparación abarca diversas ramas de esta disciplina, pero son el Jazz y el HipHop su mayor pasión, ganador del 1er lugar en la categoría de Jazz en Danzarte (concurso de Danza realizado anteriormente en Baja California hace ya algunos años).',
      'Es Director de su propia Compañía de Danza, con la cual ha llevado su pasión y estilo a diversas partes del mundo desde Taiwan o Puerto Rico, así como a gran parte de México y E.U. como las Vegas, Miami y L.A. entre otros.',
    ],
  }, {
    title: 'CORINA PERAZA',
    subtitle: 'CORINA PERAZA',
    intro: '',
    image: 'https://www.dropbox.com/s/78ttm4iz875wtir/Img-Corina-Peraza.png?dl=0',
    content: [
      'Corina es originaria de Tijuana y desde muy pequeña empezó a bailar Flamenco. Es hija de la famosa bailarina española Teresa Jaen, miembro del dueto "Teresa y Antonio Jaen". El tener a su madre como instructora, le ha ayudado a desarrollarse cada vez más a través de los años.',
      'Lleva el arte en sus venas, es por ello que Corina comparte con sus estudiantes el mismo sentimiento y pasión por el baile Flamenco. Es sabido que cualquier forma de arte se transforma en comunicación, entonces, qué mejor manera de transmitirlo tan intensamente a sus estudiantes que a través del amor y pasión del baile Flamenco.',
    ],
  }, {
    title: 'CLAUDIA LUNA',
    subtitle: 'CLAUDIA LUNA',
    intro: '',
    image: 'https://www.dropbox.com/s/u0fp0uwjuc220wq/Img_Claudia-Luna.png?dl=0',
    content: [
      'Desde que tenia 4 años inicie en el ambito de la danza, en la Escuela de Danza Gloria Campobello. Obtuve el certificado de maestra en tecnica de danza a los 16 años.',
      'La experiencia laboral ha sido en distintas instituciones como:',
      'Escuela de danza Gloria  campobello,casino de Mexicali,escuela Felix de Jesus en Mexicali,Escuela Patria,escuela Francis Parker en san Diego;actualmente cuenta con 28 años de pertenecer a la escuela de danza Pavlova como maestra de Ballet.',
      'Entre los certificados y cursos que obtenido son: Técnica en Danza, Gus Giordiano (2001), Music Workshop Unlimited de Al Gilbert, Tremaniine Dance convention (2004), Music workshop (2005), Stage 7 San Diego. Comparsa antifaz (2013), Escuela Nicte-Ha, Dance Teacher Summit (2015).',
      'He tomado clases con diferentes profesores, como Raul Martinez Tadeo, Maria del Carmen Padron, Tatiana Chevchenko, Carla Mariscal, Alberto Terreros y Gustavo Nava.',
      '"El ser Maestra le permite transmitir a sus alumnas el amor a la danza por medio de la disciplina y constancia, además de sembrar en ellos la ilusión de ser bailarinas." – Miss Claudia.',
    ],
  }, {
    title: 'MAYRA JIMÉNEZ',
    subtitle: 'MAYRA JIMÉNEZ',
    intro: '',
    image: 'https://www.dropbox.com/s/1ubs0mhib2ca80a/Img_Mayra-Jimenez.png?dl=0',
    content: [
      'Nacio el 4 de Junio del 1988. Mayra desde sus 4 años de edad comenzó a experimentar tomando clases de Jazz, y 2 años después comenzó tomando clases de ballet. Hasta la fecha sigue practicando la danza, habiendo tomado aparte de Ballet y Jazz,  clases de Contemporáneo con Miroslava Wilson y  Hip-Hop con el maestro Omar Silva dentro de la Escuela " Ballet Cámara de la Frontera" del Maestro Rafael Oseguera, habiéndose graduado como Bailarina Clásica y Contemporánea.',
      'Tiene 9 años de experiencia como Maestra impartiendo clases de Jazz, Ballet, y Lirico. Habiendo concluido con cursos de Metodología para la Danza y pedagogía.',
      'Asistiendo al 5to y 6to Congreso Nacional de Danza Jazz en Morelia Michoacán con maestros como: Guillermo Maldonado (barra al piso y pedagogía), Guillermina Gómez y John Lehrer (Jazz), Joshua Bergasse de Nueva York (jazz), Elvin Venegas de Nicaragua (técnica clásica – Ballet), Jermaine Browne de nueva York (hip-hop), Alexis Zanette de Cuba (danza moderna), entre otros. También a tomando el Curso Internacional de Danza Clásica "DANCE IT 2007 y 2008" con la primera Bailarina Irma Morales y Frank Fischer.',
      'Posteriormente obteniendo una beca para formar parte de un grupo de baile de la escuela "Culture Shock Dance Center" en San Diego. Asistio Entre el 2014 y 2015 a un curso de Jazz  y "Hells" con Yanis Marshall (bailarin y maestro Internacional) y una Materclass de ballet con la maestra Elena Tokareva Baltovick; entre otros cursos locales.',
      'Ha participado en varias obras musicales Infantiles como son "Cri-cri y la danza", "El mago de Oz", "Peter Pan", "Alicia en el país de las maravillas", como también en "La fille Mal Garde", "Graduados", "Cascanueces" y "Carmen" presentadas en el Teatro del Cecut.',
      'Su objetivo es transmitir de la manera más correcta todo lo que ha aprendido de la danza, todo lo bueno que le ha dejado e inculcar en el alumnado una disciplina y amor a la danza, a la cultura, al arte, haciéndolas sentir que es una de las mejores maneras para expresar todo aquello que nuestro cuerpo siente.',
    ],
  }, {
    title: 'ELEANA FRANCO',
    subtitle: 'ELEANA FRANCO',
    intro: '',
    image: 'https://www.dropbox.com/s/qoarklxlbpca7dg/Eleana-Franco.png?dl=0',
    content: [
      'Bailarina, coreógrafa y maestra de danza nacida en Estados Unidos. Inicio sus estudios a la edad de 2 anos en el “Colegio de Danza Sylvia” donde aprendió ballet, tap, flamenco, jazz y hip hop. Varios años después se convirtió en asistente y próximamente en maestra.',
      'Participo en varias importantes obras como es “el cascanueces” junto con la compañía “Moscow ballet” en el Civic Theatre en San Diego y también junto con la “Compañía de danza de Baja California” con Raul Tadeo. También fue participe de la obra infantil “pedro y el lobo” que fue presentada en el CECUT bajo la dirección de Norma Herrera. Continuo con sus estudios en Estados Unidos en la escuela “Coronado School of the Arts” donde estudio varios cursos de historia de la danza, nutrición, improvisación, critica de la danza, coreografía entre muchos otros.',
      'Actualmente se encuentra aplicando estos conocimientos como maestra y busca seguir creciendo para compartir este conocimiento con sus alumnos.',
    ],
  }, {
    title: 'ADRIANA CORAL',
    subtitle: 'ADRIANA CORAL',
    intro: '',
    image: 'https://www.dropbox.com/s/q4kedajs4rgdqe1/Adriana-Coral.png?dl=0',
    content: [
      'Bailarina y maestra que se desarrolla profesionalmente  en el norte de México; miembro fundador de Subterráneo Danza Contemporánea desde hace 17 años, donde su misión es exponer su trabajo como intérprete y colaborador creativo en la realización de espectáculos escénicos. Mantiene una constante búsqueda del lenguaje propio a través de la investigación en diferentes técnicas dancísticas  así como la divulgación de sus conocimientos a través de la docencia, asimismo, busca mantener vínculos estrechos con otros artistas escénicos del país para fortalecer su quehacer  dancístico y contribuir a la difusión del arte.',
    ],
  }, {
    title: 'VICKY SAENZ',
    subtitle: 'VICKY SAENZ',
    intro: '',
    image: 'https://www.dropbox.com/s/7ngb2v9j29d1xd2/Vicky-Saenz.png?dl=0',
    content: [],
  }, {
    title: 'ARIELI ZABICKY',
    subtitle: 'Arieli Zabicky',
    intro: '',
    image: 'https://www.dropbox.com/s/48fv0vg5kihbxlj/Arieli-Zabicky.JPG?dl=0',
    content: [
      'Ari Zabicky – Licenciada en danza, bailarina profesional, artista escénico, instructora.',
      'Actualmente laborando con:',
      [
        'Subterráneo Danza Contemporánea como bailarina',
        'Maestra de ballet adulto en Plan D',
        'Maestra de asignatura en Ateneo Universitario',
      ],
      'FORMACIÓN PROFESIONAL',
      ['Técnico en Danza (2010 – 2012)'],
      'Escuela de Danza Gloria Campobello, Tijuana, B.C., México',
      ['Licenciatura en Danza (2012 – 2016)'],
      'Universidad Autónoma De Baja California, Mexicali B.C, México',
      'CURSOS MÁS RECIENTES',
      '2014',
      [
        'Seminario de Metodología para la enseñanza de la Danza Clásica CEART Tijuana. Impartió: Mtro. Rafael Ocegueda',
        'Taller Intensivo de Ballet. Escuela Americana de danza, Mexicali B.C., Impartio: Aldo Kattón',
      ],
      '2015',
      [
        'Taller intensivo "DANZA JAZZ" UABC, Facultad de Artes, Mexicali. B.C., Impartido por: Pedro Garcia Malvaez',
        'Master Class de partnering Facultad de Artes UABC, Licenciatura En danza Impartió Lux Boreal',
        'Congreso Nacional de Danza Jazz – CRAM, Zam. Mich.',
      ],
      '2016',
      [
        'Capacitación en "Contrología" o Método Pilates Nivel 1, Fitness Center, Mexicali B.C., Impartió: Lic. Eunice Hidalgo Palacios',
        'Taller "El cuerpo vacío" Dance Lab, Tijuana, Impartió: Shantí Vera',
      ],
      '2017',
      [
        'Taller de Metodo Feldenkrais "El Huerto Playas de Tijuana" Impartió: Kata Cots',
      ],
      'PARTICIPACIONES',
      '2015',
      [
        'Bailarina invitada en grupo de danza "La Pieza Danza Jazz", Concurso dentro del marco del Congreso Internacional de Danza Jazz Zamora, Michoacán. Participación con la coreografía "CUERPOS", Coreógrafo: Ricardo Zavala, PRIMER LUGAR',
      ],
      '2016',
      [
        'Bailarina en grupo de danza "La Pieza Danza Jazz", Coreografía: Obscuridad Coreógrafo: Ricardo Zavala, Presentación de exhibición en el 8vo concurso del Congreso Internacional de Danza Jazz – Zamora, Michoacán',
        'Bailarina en Grupo de danza "La Pieza Danza Jazz".<br />Obra: "Méjico, una chicanada más".<br />- Bailarina.<br />- Gestión.<br />- Asistente de producción.<br />Dirección general: Ricardo Zavala.<br />Presentaciones:<br />- Teatro UABC, Mexicali B.C.<br />- Teatro Obrero, Zamora Michoacán dentro de Congreso Nacional de Danza Jazz.',
        'Colaboración como bailarina invitada con compañía de danza Bajo la Lápida.<br />Coreógrafo: Armando Leal.<br />Participación en evento de ARMONIA UABC – 2016',
        'OBRA: "Homa´quina".<br />Coreógrafo: Emma G. Davis.<br />Proyecto coreográfico de la Lic. En danza UABC – Mexicali.<br />Estreno: 3 de Junio 2016.<br />- Bailarina.<br />- Gestión.<br />- Montaje coreográfico y de iluminación',
        'Montajes de iluminación en Festival Internacional de Danza Entre Fronteras UABC, Mexicali B.C.<br />- "Quasar" compañía de danza<br />- Taller coreográfico de la UABC<br />Antares Danza contemporánea, Responsable: Hildelena Vazquez',
        'Participación en el taller "Body mind centering"<br />Lic. En Danza, UABC<br />Impartió: Tamar Kipnis',
        'Bailarina en la pieza: "Mis amigos me dicen.."<br />Coreografa: Rosa A. Gomez<br />Actividad dentro de Facultad de Artes UABC',
        'Entijuanarte<br />Montaje de iluminación y traspunte en: "Piezas desordenadas"<br />bajo la dirección de Gregorio Coral',
      ],
      '2017',
      [
        'Bailarina invitada en Subterraneo Danza contemporánea',
        'Bailarina en la obra: Caleidoscopio<br />Direccion: Gregorio Coral',
      ],
    ],
  }, {
    title: 'MARILU AGUILAR',
    subtitle: 'Marilu Aguilar',
    intro: '',
    image: 'https://www.dropbox.com/s/4lcs5yak57cd1sb/user_placeholder.png?dl=0',
    content: [],
  }, {
    title: 'GIOVANI GONZÁLEZ ALARCÓN',
    subtitle: 'GIOVANI GONZÁLEZ ALARCÓN',
    intro: '',
    image: '/images/escuela/staff/giovani-alarcon.jpg',
    content: [
      'Egresado de la Lic. en Actividad Física y Deporte por la Universidad Autónoma de Baja California, con amplia experiencia en presentaciones profesionales incluyendo participación en shows de la cadena televisiva Telemundo, eventos masivos en Los Ángeles y en Baja California, incluyendo apertura de múltiples conciertos de artistas en la región.',
      'Impartió clases de Cardio Dance y Cardio Hip Hop en diversos gimnasios de la Ciudad de Tijuana. Maestro de Hip-Jazz en los principales estudios de Danza en Tijuana.',
      'Coreógrafo Profesional, forma parte de la compañía de Hip Hop "Culture Shock" en San Diego.',
    ],
  }, {
    title: 'MÓNICA ZITLALI GARZA MAYORAL',
    subtitle: 'MÓNICA ZITLALI GARZA MAYORAL',
    intro: '',
    image: '/images/escuela/staff/monica-zitlali.png',
    content: [
      'Técnico en Danza y Maestra en Educación egresada de CETYS Universidad, Licenciada en Filosofía y en Ciencias de la Educación, tiene una vasta experiencia en el ámbito docente de danza clásica y ballet, ejerciendo profesionalmente en organizaciones como el CEART, Hospital Infantil de las Californias, CECUTEC, estudios de danza y colegios en la región.',
    ],
  }],
};
